# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b075287c516833d8abfded39ec10755c141b4dc4f604b9a51b0e704fc247b4eaf455955cf8f2f4565a7c59083325c7f99870a6a4fa9c8f5b52ab58f544a65f9

test:
  secret_key_base: ddbbf3ded110ee73b85fe0de03458c429ae33995c0a3ce5d9b4b9d53465cad001e39707df29ae31c3619bbb71975f1d5ea1518f462b72aa00309ba269aea7787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
